# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files

-   repo: https://github.com/psf/black
    rev: 23.12.1 # Or match the version in requirements.txt/pyproject.toml
    hooks:
    -   id: black
        language_version: python3.11

-   repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version. Must be aligned with the version in requirements.txt
    rev: v0.1.9 # Or match the version in requirements.txt
    hooks:
    # Run the formatter.
    -   id: ruff-format
        types_or: [python, pyi, jupyter]
    # Run the linter.
    -   id: ruff
        types_or: [python, pyi, jupyter]
        args: [--fix, --exit-non-zero-on-fix] # Auto-fix and fail if fixes are made
